### ISSUE TITLE
Morgan

### ISSUE THREAD

**Issue by weldermarcosxd** [luizguilhermesj/generic-rest-api#1]
Is there a way to use Morgan for log instead of the raw executed query?

awesome project by the way,
thanks

**Comment by weldermarcosxd** [comment]
Solved

**Comment by luizguilhermesj** [comment]
Hey @weldermarcosxd, thanks!
Can you tell us how did you solved it?

**Comment by weldermarcosxd** [comment]
Hey @luizguilhermesj, 

First thing I needed to mute the raw queries executed by the sequelize is passing the logging option to false in the config.json file:

`  "development": {
        "username": "username",
        "password": "pass",
        "database": "database",
        "host": "127.0.0.1",
        "dialect": "mysql",
        "logging": false, 
        "define": {
              "timestamps": false
        }
  }`

To use logs in morgan you can use just like the docs explain in the examples.

[Examples](https://www.npmjs.com/package/morgan#examples)
